{
 "title": "PerfSonar",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "label": "Source:" },
   { "name": "destination", "label": "Destination:" }
  ]
 },
 "panels": [
  { "title": "General View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Packet Loss Rate",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(network_packet_loss_rate{source=\"$source\", destination=\"$destination\"}*100)"
    }
   ]
  },
  {
   "title": "TTL",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_histogram_ttl{source=\"$source\", destination=\"$destination\"}"
    }
   ]
  },
  {
   "title": "Time Error Estimates",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_time_error_estimates{source=\"$source\", destination=\"$destination\"}"
    }
   ]
  },
  {
   "title": "Packet Duplicates",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_packet_duplicates{source=\"$source\", destination=\"$destination\"}",
     "legendFormat": "Packet Duplicates"
    }
   ]
  },
  {
   "title": "Packet Reorders",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_packet_duplicates{source=\"$source\", destination=\"$destination\"}"
    }
   ]
  },
  { "title": "Detailed Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Throuput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "network_throughput{source=\"$source\", destination=\"$destination\"}",
     "legendFormat": "Protocol {{protocol}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "network_histogram_owdelay_statistics_0{destination=\"$destination\", source=\"$source\", key=\"median\"}",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "RTT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "network_histogram_rtt_statistics_3600{source=\"$source\", destination=\"$destination\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "network_histogram_owdelay_statistics_0{source=\"$source\", destination=\"$destination\", key=\"percentile-95\"}-  on () network_histogram_owdelay_statistics_0{source=\"$source\", destination=\"$destination\", key=\"median\"}",
     "legendFormat": "P95 - P50"
    },
    {
     "expr": "network_histogram_owdelay_statistics_0{source=\"$source\", destination=\"$destination\", key=\"percentile-75\"}-  on () network_histogram_owdelay_statistics_0{source=\"$source\", destination=\"$destination\", key=\"percentile-25\"}",
     "legendFormat": "P75 - P25"
    },
    {
     "expr": "network_histogram_owdelay_statistics_0{source=\"$source\", destination=\"$destination\", key=\"variance\"}",
     "legendFormat": "Variance"
    },
    {
     "expr": "network_histogram_owdelay_statistics_0{source=\"$source\", destination=\"$destination\", key=\"standard-deviation\"}",
     "legendFormat": "Std Deviation"
    }
   ]
  }
 ]
}